const TYPES_REGISTER_FORM = {
  CHANGE_NAME: 'CHANGE_NAME',
  CHANGE_LAST_NAME: 'CHANGE_LAST_NAME',
  CHANGE_BIRTH_DATE: 'CHANGE_BIRTH_DATE',
  CHANGE_PROJECT: 'CHANGE_PROJECT',
  CHANGE_CODE: 'CHANGE_CODE',
  CHANGE_DOCUMENT: 'CHANGE_DOCUMENT',
  CHANGE_NUMBER_DOCUMENT: 'CHANGE_NUMBER_DOCUMENT',
  CHANGE_EMAIL: 'CHANGE_EMAIL',
  CHANGE_INSTITUTIONAL_EMAIL: 'CHANGE_INSTITUTIONAL_EMAIL',
  CHANGE_PHONE: 'CHANGE_PHONE',
  CHANGE_INSTRUMENT: 'CHANGE_INSTRUMENT'
}

export { TYPES_REGISTER_FORM }
