const TYPES_REGISTER_FORM = {
  CHANGE_NAME: 'CHANGE_NAME',
  CHANGE_LAST_NAME: 'CHANGE_LAST_NAME',
  CHANGE_EMAIL: 'CHANGE_EMAIL',
  CHANGE_ID: 'CHANGE_ID',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD'
}

export { TYPES_REGISTER_FORM }
